# Generated by Django 2.2.1 on 2019-05-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
